const $=id=>document.getElementById(id), movie=$("movie"), room=new URLSearchParams(location.search).get("room")||"LOVE1234";
$("roomCode").textContent=room; const ws=new WebSocket((location.protocol==="https:"?"wss":"ws")+"://"+location.host+"/ws"); ws.onopen=()=>ws.send(JSON.stringify({type:"join",room}));
const send=m=>ws.readyState===1&&ws.send(JSON.stringify({...m,room}));
$("file").onchange=async()=>{let f=$("file").files[0];if(!f)return;let fd=new FormData;fd.append("movie",f);let d=await(await fetch("/upload",{method:"POST",body:fd})).json();movie.src=d.url;$("empty").style.display="none";send({type:"movie",url:d.url})};
$("play").onclick=()=>movie.paused?movie.play():movie.pause();$("back").onclick=()=>movie.currentTime=Math.max(0,movie.currentTime-10);$("fwd").onclick=()=>movie.currentTime+=10;$("mute").onclick=()=>movie.muted=!movie.muted;$("vol").oninput=e=>movie.volume=e.target.value;
movie.onplay=()=>send({type:"sync",a:"play",t:movie.currentTime});movie.onpause=()=>send({type:"sync",a:"pause",t:movie.currentTime});movie.onseeked=()=>send({type:"sync",a:"seek",t:movie.currentTime});
ws.onmessage=async e=>{let m=JSON.parse(e.data);if(m.type==="movie"){movie.src=m.url;$("empty").style.display="none"}if(m.type==="sync"){movie.currentTime=m.t;if(m.a==="play")movie.play().catch(()=>{});if(m.a==="pause")movie.pause()}if(m.type==="chat")msg("Hooria",m.text);if(m.type==="offer"){await media();await peerMake(false);await peer.setRemoteDescription(m.o);let a=await peer.createAnswer();await peer.setLocalDescription(a);send({type:"answer",a})}if(m.type==="answer")await peer?.setRemoteDescription(m.a);if(m.type==="ice")await peer?.addIceCandidate(m.c).catch(()=>{})};
function msg(w,t){let d=document.createElement("div");d.className="msg";d.textContent=w+": "+t;$("msgs").append(d)}$("form").onsubmit=e=>{e.preventDefault();let t=$("text").value.trim();if(t){msg("You",t);send({type:"chat",text:t});$("text").value=""}};
let stream,peer;async function media(){if(!stream)stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true})}async function peerMake(init){peer=new RTCPeerConnection({iceServers:[{urls:"stun:stun.l.google.com:19302"}]});stream.getTracks().forEach(t=>peer.addTrack(t,stream));peer.ontrack=e=>$("remote").srcObject=e.streams[0];peer.onicecandidate=e=>e.candidate&&send({type:"ice",c:e.candidate});if(init){let o=await peer.createOffer();await peer.setLocalDescription(o);send({type:"offer",o})}}
$("startCall").onclick=async()=>{await media();await peerMake(true)};$("endCall").onclick=()=>{peer?.close();peer=null;$("remote").srcObject=null};$("cam").onclick=async()=>{await media();stream.getVideoTracks()[0].enabled=!stream.getVideoTracks()[0].enabled};$("mic").onclick=async()=>{await media();stream.getAudioTracks()[0].enabled=!stream.getAudioTracks()[0].enabled};$("invite").onclick=async()=>{await navigator.clipboard.writeText(location.origin+"/?room="+room);alert("Room link copied ❤️")};